#!/usr/bin/env bash
# droplet_pipeline.sh — Generate (or update) .github/workflows/publish-droplet.yml
# and commit it.  With --dry-run, print the YAML to stdout only.
#
# Usage:
#   droplet_pipeline.sh --target <name> [--config <path>] [--dry-run] [--non-interactive]
#
# Exit codes:
#   0  success
#   2  pre-flight failure (bad args, missing tools)
#   4  validation failure (missing required config fields)

set -euo pipefail

EXIT_PRE_FLIGHT=2
EXIT_ENV_INVALID=4

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Resolve repo root
# ---------------------------------------------------------------------------
if REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
fi

# ---------------------------------------------------------------------------
# Source shared helpers
# ---------------------------------------------------------------------------
# shellcheck source=publish_common.sh
source "${SCRIPT_DIR}/publish_common.sh"

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
TARGET_NAME=""
CONFIG_PATH=""
DRY_RUN=0
NON_INTERACTIVE=0

usage() {
  cat <<'USAGE'
Usage: droplet_pipeline.sh --target <name> [--config <path>] [--dry-run] [--non-interactive]
USAGE
}

fail_pre() {
  printf 'droplet pipeline pre-flight failure: %s\n' "$1" >&2
  exit "${EXIT_PRE_FLIGHT}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      [[ $# -ge 2 ]] || fail_pre "--target requires a value"
      TARGET_NAME="$2"
      shift 2
      ;;
    --target=*)
      TARGET_NAME="${1#*=}"
      shift
      ;;
    --config)
      [[ $# -ge 2 ]] || fail_pre "--config requires a value"
      CONFIG_PATH="$2"
      shift 2
      ;;
    --config=*)
      CONFIG_PATH="${1#*=}"
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --non-interactive)
      NON_INTERACTIVE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      fail_pre "unknown option: $1"
      ;;
  esac
done

# Silence unused-variable warning; flag is reserved for CI callers.
: "${NON_INTERACTIVE:=0}"

[[ -n "${TARGET_NAME}" ]] || fail_pre "--target <name> is required"

# ---------------------------------------------------------------------------
# Resolve config path
# ---------------------------------------------------------------------------
if [[ -z "${CONFIG_PATH}" ]]; then
  if [[ -f "${REPO_ROOT}/publish.json" ]]; then
    CONFIG_PATH="${REPO_ROOT}/publish.json"
  elif [[ -f "${REPO_ROOT}/project/configs/publish.json" ]]; then
    CONFIG_PATH="${REPO_ROOT}/project/configs/publish.json"
  else
    fail_pre "publish.json not found at '${REPO_ROOT}/publish.json' or '${REPO_ROOT}/project/configs/publish.json'"
  fi
fi

[[ -f "${CONFIG_PATH}" ]] || fail_pre "publish config not found at '${CONFIG_PATH}'"
command -v jq >/dev/null 2>&1 || fail_pre "jq is required but not found on PATH"

# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------
if ! bash "${SCRIPT_DIR}/validate_droplet_env.sh" "${CONFIG_PATH}" "${TARGET_NAME}"; then
  exit "${EXIT_ENV_INVALID}"
fi

# ---------------------------------------------------------------------------
# Extract config values
# ---------------------------------------------------------------------------
TARGET_JSON="$(jq -c --arg t "${TARGET_NAME}" \
  '.targets[]? | select(.name == $t and .type == "droplet")' \
  "${CONFIG_PATH}")"

DEPLOY_PATH="$(printf '%s' "${TARGET_JSON}" | jq -r '.droplet.deploy_path')"
DEPLOY_BRANCH="$(printf '%s' "${TARGET_JSON}" | jq -r '.droplet.deploy_branch')"
BUILD_CMD="$(printf '%s' "${TARGET_JSON}" | jq -r '.droplet.build_cmd // empty')"
START_CMD="$(printf '%s' "${TARGET_JSON}" | jq -r '.droplet.start_cmd')"
GITHUB_REPO="$(printf '%s' "${TARGET_JSON}" | jq -r '.droplet.github_repo')"
SSH_KEY_SECRET="$(printf '%s' "${TARGET_JSON}" | jq -r '.secrets.ssh_key_secret')"
KNOWN_HOSTS_SECRET="$(printf '%s' "${TARGET_JSON}" | jq -r '.secrets.known_hosts_secret')"

# Conventional GH Actions secret names for host/user/port
SSH_HOST_SECRET="DROPLET_SSH_HOST"
SSH_USER_SECRET="DROPLET_SSH_USER"
SSH_PORT_SECRET="DROPLET_SSH_PORT"

# Keep GITHUB_REPO available for callers / future gh-trigger use.
: "${GITHUB_REPO}"

# ---------------------------------------------------------------------------
# Generate workflow YAML
# ---------------------------------------------------------------------------
WORKFLOW_HEADER="$(cat <<EOF
# Generated by /publish droplet pipeline -- do not edit manually
name: "Publish -- ${TARGET_NAME} (Droplet)"
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        # appleboy/ssh-action pinned SHA: 4a13f365c4cb2c5a7b0a2e0a54db7a4a7b5f6fd1
        uses: appleboy/ssh-action@4a13f365c4cb2c5a7b0a2e0a54db7a4a7b5f6fd1
        with:
          host: \${{ secrets.${SSH_HOST_SECRET} }}
          username: \${{ secrets.${SSH_USER_SECRET} }}
          port: \${{ secrets.${SSH_PORT_SECRET} }}
          key: \${{ secrets.${SSH_KEY_SECRET} }}
          known_hosts: \${{ secrets.${KNOWN_HOSTS_SECRET} }}
          script: |
            cd ${DEPLOY_PATH}
            git pull origin ${DEPLOY_BRANCH}
EOF
)"

# Build the script block lines separately so newlines are always present
SCRIPT_LINES=""
if [[ -n "${BUILD_CMD}" ]]; then
  SCRIPT_LINES+="            ${BUILD_CMD}"$'\n'
fi
SCRIPT_LINES+="            ${START_CMD}"$'\n'

WORKFLOW_YAML="${WORKFLOW_HEADER}"$'\n'"${SCRIPT_LINES}"

# ---------------------------------------------------------------------------
# Dry-run: print and exit
# ---------------------------------------------------------------------------
if (( DRY_RUN )); then
  printf '%s' "${WORKFLOW_YAML}"
  exit 0
fi

# ---------------------------------------------------------------------------
# Write workflow file
# ---------------------------------------------------------------------------
WORKFLOW_DIR="${REPO_ROOT}/.github/workflows"
WORKFLOW_FILE="${WORKFLOW_DIR}/publish-droplet.yml"

mkdir -p "${WORKFLOW_DIR}"
printf '%s' "${WORKFLOW_YAML}" > "${WORKFLOW_FILE}"

# Commit only when the file actually changed
if git -C "${REPO_ROOT}" diff --quiet -- ".github/workflows/publish-droplet.yml" 2>/dev/null && \
   git -C "${REPO_ROOT}" diff --cached --quiet -- ".github/workflows/publish-droplet.yml" 2>/dev/null && \
   git -C "${REPO_ROOT}" ls-files --error-unmatch ".github/workflows/publish-droplet.yml" >/dev/null 2>&1; then
  printf 'Workflow unchanged, skipping commit.\n'
  exit 0
fi

git -C "${REPO_ROOT}" add ".github/workflows/publish-droplet.yml"
git -C "${REPO_ROOT}" commit -m "chore(publish): update droplet workflow for target ${TARGET_NAME}"
printf 'Workflow committed: %s\n' "${WORKFLOW_FILE}"
