// ESLint configuration for Skolkartan.
//
// PRETTIER OWNS FORMATTING; ESLINT NEVER REPORTS A FORMATTING RULE.
// The two tools overlap by default, and the overlap produces contradictory autofixes: one tool's
// fix is the other tool's violation, so the developer ends up running them alternately forever.
// `eslint-config-prettier` is therefore the LAST element of the exported array, switching off every
// stylistic rule the earlier layers turned on. If a diff is about whitespace, quotes or line width,
// Prettier decides. If it is about correctness, ESLint decides.
//
// TYPE-AWARE LINTING IS ON, AND IT IS SLOWER ON PURPOSE.
// `recommendedTypeChecked` requires the linter to build a TypeScript program, which costs
// noticeably more than syntactic linting. It is accepted because the rules it unlocks —
// `no-floating-promises` and `no-misused-promises` above all — catch a class of bug that no amount
// of syntactic linting can see, and an ingestion codebase full of async work is exactly where those
// bugs live.
//
// `eslint-config-next` is consumed through its NATIVE FLAT-CONFIG EXPORT, not through
// `@eslint/eslintrc`'s `FlatCompat`. eslint-config-next 16 exports a flat-config array directly, so
// the compatibility shim is unnecessary; recorded here so the next reader does not have to
// reverse-engineer which path was taken.
//
// TYPESCRIPT IS PINNED TO 6.x FOR THIS TOOLCHAIN. typescript-eslint 8.67 declares a peer range of
// `>=4.8.4 <6.1.0`. TypeScript 7 (the native compiler) is outside it, and no typescript-eslint
// release supports 7 yet. Type-aware linting is the point of this configuration, so the project
// stays one major behind on TypeScript rather than giving it up. See docs/decisions.md.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import next from 'eslint-config-next';
import prettier from 'eslint-config-prettier';

const config = [
  {
    ignores: [
      'node_modules/', // third-party code; not ours to lint
      '.next/', // Next.js build output, regenerated on every build
      'out/', // Next.js static export output, regenerated on every export
      'next-env.d.ts', // generated by Next, not authored here
      'project/', // the scrum board is Markdown and JSON, not source

      // Agent harness. Both directories ship JavaScript (`skills/self-sync/scripts/run.js`), which
      // ESLint reaches by default even though the leading dot suggests otherwise. `.prettierignore`
      // already excludes them for the same reason: the harness authors and rewrites these files
      // outside this repository's source conventions, so a harness upgrade shipping a lint
      // violation would turn `npm run lint` — and, from E00_S04, the merge gate — red for code no
      // author here owns or may edit. The two ignore lists must agree; before E00_S02_T04 they did
      // not.
      '.claude/',
      '.agents/',
    ],
  },

  js.configs.recommended,

  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Type-aware rules need a tsconfig entry for the file being linted. This config file and any
  // other plain JavaScript is not in the TypeScript program, so linting it would fail for want of
  // a project entry. Turn the type-aware layer off for those files only.
  {
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },

  ...next,

  prettier,
];

export default config;
