#!/usr/bin/env bash
# npm_ci_pipeline.sh — Generate (or update) a GitHub Actions workflow for npm
# publishing via OIDC Trusted Publishers, commit it, and trigger it with gh.
#
# Usage:
#   npm_ci_pipeline.sh --target <name> --config <path> [--dry-run]
#
# Exit codes:
#   0  success (or --dry-run completed cleanly)
#   3  workflow trigger failure (gh workflow run exited non-zero)
#   4  config or environment invalid

set -euo pipefail

EXIT_ENV_INVALID=4
EXIT_TRIGGER_FAILED=3

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Resolve repo root
# ---------------------------------------------------------------------------
if REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
fi

# ---------------------------------------------------------------------------
# Source shared helpers
# ---------------------------------------------------------------------------
# shellcheck source=publish_common.sh
source "${SCRIPT_DIR}/publish_common.sh"

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
TARGET_NAME=""
CONFIG_PATH=""
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage: npm_ci_pipeline.sh --target <name> --config <path> [--dry-run]
USAGE
}

fail_usage() {
  usage >&2
  printf 'npm-ci pipeline error: %s\n' "$1" >&2
  exit "${EXIT_ENV_INVALID}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      [[ $# -ge 2 ]] || fail_usage "--target requires a value"
      TARGET_NAME="$2"
      shift 2
      ;;
    --target=*)
      TARGET_NAME="${1#*=}"
      shift
      ;;
    --config)
      [[ $# -ge 2 ]] || fail_usage "--config requires a value"
      CONFIG_PATH="$2"
      shift 2
      ;;
    --config=*)
      CONFIG_PATH="${1#*=}"
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail_usage "unknown option: $1"
      ;;
  esac
done

[[ -n "${TARGET_NAME}" ]] || fail_usage "--target <name> is required"

# ---------------------------------------------------------------------------
# Resolve config path
# ---------------------------------------------------------------------------
if [[ -z "${CONFIG_PATH}" ]]; then
  if [[ -f "${REPO_ROOT}/publish.json" ]]; then
    CONFIG_PATH="${REPO_ROOT}/publish.json"
  elif [[ -f "${REPO_ROOT}/project/configs/publish.json" ]]; then
    CONFIG_PATH="${REPO_ROOT}/project/configs/publish.json"
  else
    fail_usage "publish.json not found at '${REPO_ROOT}/publish.json' or '${REPO_ROOT}/project/configs/publish.json'"
  fi
fi

[[ -f "${CONFIG_PATH}" ]] || fail_usage "publish config not found at '${CONFIG_PATH}'"
command -v jq >/dev/null 2>&1 || fail_usage "jq is required but not found on PATH"

# ---------------------------------------------------------------------------
# Phase: validate
# ---------------------------------------------------------------------------
printf '[validate] checking environment and config...\n'
if ! bash "${SCRIPT_DIR}/validate_npm_ci_env.sh" "${CONFIG_PATH}" "${TARGET_NAME}"; then
  exit "${EXIT_ENV_INVALID}"
fi

# ---------------------------------------------------------------------------
# Extract config values
# ---------------------------------------------------------------------------
TARGET_JSON="$(jq -c --arg t "${TARGET_NAME}" \
  '.targets[]? | select(.name == $t and .type == "npm-ci")' \
  "${CONFIG_PATH}")"

GITHUB_REPO="$(printf '%s' "${TARGET_JSON}" | jq -r '.github_repo')"
WORKFLOW_PATH="$(printf '%s' "${TARGET_JSON}" | jq -r '.workflow_path // ".github/workflows/npm-publish.yml"')"
PACKAGE_NAME="$(printf '%s' "${TARGET_JSON}" | jq -r '.npm.package_name')"
NPM_ACCESS="$(printf '%s' "${TARGET_JSON}" | jq -r '.npm.access')"
DIST_TAG="$(printf '%s' "${TARGET_JSON}" | jq -r '.npm.dist_tag // "latest"')"

WORKFLOW_FILENAME="$(basename "${WORKFLOW_PATH}")"

# Resolve workflow file to absolute path
if [[ "${WORKFLOW_PATH}" = /* ]]; then
  WORKFLOW_FILE="${WORKFLOW_PATH}"
else
  WORKFLOW_FILE="${REPO_ROOT}/${WORKFLOW_PATH}"
fi
WORKFLOW_DIR="$(dirname "${WORKFLOW_FILE}")"

# Relative path for git operations (relative to REPO_ROOT)
WORKFLOW_FILE_REL="${WORKFLOW_PATH#./}"

# ---------------------------------------------------------------------------
# Phase: generate-workflow
# ---------------------------------------------------------------------------
printf '[generate-workflow] rendering workflow YAML...\n'

WORKFLOW_YAML="$(cat <<EOF
# Generated by /publish npm-ci pipeline — do not edit manually
name: "Publish — ${PACKAGE_NAME}"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish --provenance --access ${NPM_ACCESS} --tag ${DIST_TAG}
EOF
)"

# ---------------------------------------------------------------------------
# Dry-run: print YAML and exit
# ---------------------------------------------------------------------------
if (( DRY_RUN )); then
  printf '[generate-workflow] dry-run — printing YAML only (no file written, no commit, no trigger)\n'
  printf '%s\n' "${WORKFLOW_YAML}"
  exit 0
fi

# ---------------------------------------------------------------------------
# Phase: commit-workflow
# ---------------------------------------------------------------------------
printf '[commit-workflow] writing workflow file...\n'

mkdir -p "${WORKFLOW_DIR}"
printf '%s\n' "${WORKFLOW_YAML}" > "${WORKFLOW_FILE}"

if git -C "${REPO_ROOT}" diff --quiet -- "${WORKFLOW_FILE_REL}" 2>/dev/null && \
   git -C "${REPO_ROOT}" diff --cached --quiet -- "${WORKFLOW_FILE_REL}" 2>/dev/null && \
   git -C "${REPO_ROOT}" ls-files --error-unmatch "${WORKFLOW_FILE_REL}" >/dev/null 2>&1; then
  printf '[commit-workflow] no changes — skipping commit\n'
else
  git -C "${REPO_ROOT}" add "${WORKFLOW_FILE_REL}"
  git -C "${REPO_ROOT}" commit -m "chore(publish): update npm CI workflow for target ${TARGET_NAME}"
  printf '[commit-workflow] committed: %s\n' "${WORKFLOW_FILE}"
fi

# ---------------------------------------------------------------------------
# Phase: trigger
# ---------------------------------------------------------------------------
printf '[trigger] dispatching workflow run...\n'

if ! gh workflow run "${WORKFLOW_FILENAME}" --repo "${GITHUB_REPO}"; then
  printf '[trigger] ERROR: gh workflow run failed\n' >&2
  exit "${EXIT_TRIGGER_FAILED}"
fi

RUN_URL="$(gh run list \
  --workflow "${WORKFLOW_FILENAME}" \
  --repo "${GITHUB_REPO}" \
  --limit 1 \
  --json url \
  --jq '.[0].url')"

printf '%s\n' "${RUN_URL}"

# ---------------------------------------------------------------------------
# Phase: triggered
# ---------------------------------------------------------------------------
printf '[triggered] workflow run dispatched: %s\n' "${RUN_URL}"
